drop table if exists HHSurvey.TripDim2014
create table HHSurvey.TripDim2014 (
	[TripDimID] [BIGINT]
	,[ocnty] [varchar](100)
	,[dcnty] [varchar](100)
	,[o_purpose] [varchar](100)
	,[d_purpose] [varchar](100)
	,[mode] [varchar](100)
	,[triptype] [varchar](100)
	,[mode2] [varchar](100)
	,[last] [varchar](100)
	,[time_start_past] [varchar](20)
	,[time_end_past] [varchar](20)
	,[taxi_type] [varchar](100)
	,[taxi_fare] [varchar](100)
	,[vehicle] [varchar](100)
	,[driver] [varchar](100)
	,[toll] [varchar](100)
	,[pool_start] [varchar](100)
	,[pr_lot1_a] [varchar](200)
	,[change_vehicles] [varchar](100)
	,[park] [varchar](100)
	,[pr_lot2_a] [varchar](200)
	,[park_pay] [varchar](100)
	,[mode_acc] [varchar](100)
	,[mode_egr] [varchar](100)
	,[transitsystem1] [varchar](100)
	,[transitsystem2] [varchar](100)
	,[transitsystem3] [varchar](100)
	,[transitsystem4] [varchar](100)
	,[mode3] [varchar](100)
	,[mmode] [varchar](100)
	,[time_cat] [varchar](100)
	,[time_day] [varchar](100)
	,[mtime_cat] [varchar](100)
	,[mtime_day] [varchar](100)
	,[distcat] [varchar](100)
	,[dataset] [varchar](100)
	,[hhid] [BIGINT]
	,[personID] [BIGINT]
	,[tripID] [BIGINT]
	,[pernum] [TINYINT]
	,[tripnum] [TINYINT]
	,[total_trip] [TINYINT]
	,[trip_dur_reported] [SMALLINT]
	,[implied_speed_mph] [SMALLINT]
	,[a_dur] [SMALLINT]
	,[ozip] [INT]
	,[dzip] [INT]
	,[time_start_mam] [INT]
	,[time_end_mam] [INT]
	,[gdist] [FLOAT]
	,[gtime] [FLOAT]
	,[travelers_total] [TINYINT]
	,[travelers_hh] [FLOAT]
	,[travelers_nonhh] [FLOAT]
	,[pr_lot1] [INT]
	,[pr_lot2] [INT]
	,[transitline1] [INT]
	,[transitline2] [INT]
	,[transitline3] [INT]
	,[transitline4] [INT]
	,[member6] [BIGINT]
	,[member7] [BIGINT]
	,[member8] [BIGINT]
	,[o_pumace10] [INT]
	,[d_pumace10] [INT]
	,[num_trips_linked] [TINYINT]
	,[expwt_final] [FLOAT]
	,[recordID] [varchar](100)
	,[ocity] [varchar](100)
	,[ostate] [varchar](100)
	,[dcity] [varchar](100)
	,[dstate] [varchar](100)
	,[time_start_hhmm] [varchar](100)
	,[time_end_hhmm] [varchar](100)
	,[member1] [varchar](100)
	,[member2] [varchar](100)
	,[member3] [varchar](100)
	,[member4] [varchar](100)
	,[member5] [varchar](100)
	,[o_tract] [varchar](100)
	,[o_bg] [varchar](100)
	,[o_rgc_name] [varchar](100)
	,[d_tract] [varchar](100)
	,[d_bg] [varchar](100)
	,[d_rgc_name] [varchar](100)
	,[mtime] [varchar](100)
	,[combined_modes] [varchar](100)
	,[DWCHECKSUM] BIGINT
 CONSTRAINT [PK_TripDim2014] PRIMARY KEY CLUSTERED (TripDimID)
)