drop table if exists HHSurvey.TripDim2015
create table HHSurvey.TripDim2015 (
	[TripDimID] [BIGINT]
	,[recordID] [varchar](100)
	,[hhid] [BIGINT]
	,[personID] [BIT]
	,[tripID] [BIGINT]
	,[pernum] [TINYINT]
	,[tripnum] [TINYINT]
	,[tottrip] [TINYINT]
	,[last] [TINYINT]
	,[cnty_start] [TINYINT]
	,[city_start] [varchar](100)
	,[zip_start] [INT]
	,[state_start] [varchar](100)
	,[cnty_end] [TINYINT]
	,[city_end] [varchar](100)
	,[zip_end] [INT]
	,[state_end] [varchar](100)
	,[time_start_mam] [SMALLINT]
	,[time_start_hhmm] [varchar](100)
	,[time_end_mam] [SMALLINT]
	,[time_end_hhmm] [varchar](100)
	,[trip_dur_reported] [SMALLINT]
	,[gdist] [FLOAT]
	,[gtime] [FLOAT]
	,[implied_speed_mph] [FLOAT]
	,[a_dur] [INT]
	,[o_purpose] [varchar](100)
	,[d_purpose] [varchar](100)
	,[mode] [varchar](100)
	,[travelers_total] [TINYINT]
	,[travelers_hh] [TINYINT]
	,[travelers_nonhh] [TINYINT]
	,[taxi_type] [varchar](100)
	,[taxi_fare] [varchar](100)
	,[bikeshare] [varchar](100)
	,[vehicle] [varchar](100)
	,[driver] [varchar](100)
	,[toll] [varchar](100)
	,[pool_start] [varchar](100)
	,[pr_lot1_a] [varchar](200)
	,[pr_lot1] [FLOAT]
	,[change_vehicles] [varchar](100)
	,[park] [varchar](100)
	,[park_loc_dur] [TINYINT]
	,[park_loc_dis] [FLOAT]
	,[pr_lot2_a] [varchar](200)
	,[pr_lot2] [FLOAT]
	,[park_pay] [varchar](100)
	,[mode_acc] [varchar](100)
	,[mode_egr] [varchar](100)
	,[transitsystem1] [varchar](100)
	,[transitsystem2] [varchar](100)
	,[transitsystem3] [varchar](100)
	,[transitsystem4] [varchar](100)
	,[transitsystem5] [INT]
	,[transitline1] [FLOAT]
	,[transitline2] [FLOAT]
	,[transitline3] [FLOAT]
	,[transitline4] [SMALLINT]
	,[transitline5] [INT]
	,[member1] [FLOAT]
	,[member2] [FLOAT]
	,[member3] [FLOAT]
	,[member4] [FLOAT]
	,[member5] [FLOAT]
	,[member6] [FLOAT]
	,[member7] [FLOAT]
	,[member8] [INT]
	,[prepop] [varchar](20)
	,[childunder5_originaltripid] [FLOAT]
	,[child_under5] [varchar](20)
	,[num_trips_linked] [TINYINT]
	,[combined_modes] [varchar](100)
	,[o_tract] [INT]
	,[o_bg] [bigINT]
	,[o_puma10] [INT]
	,[o_taz2010] [SMALLINT]
	,[o_rgc_name] [varchar](100)
	,[d_tract] [INT]
	,[d_bg] [BIGINT]
	,[d_puma10] [INT]
	,[d_taz2010] [SMALLINT]
	,[d_rgc_name] [varchar](100)
	,[expwt_h1415] [FLOAT]
	,[DWCHECKSUM] BIGINT
 CONSTRAINT [PK_TripDim2015] PRIMARY KEY CLUSTERED (TripDimID)
)