USE [Elmer]
GO

/****** Object:  StoredProcedure [HHSurvey].[mergeHouseholdDim2014]    Script Date: 9/12/2019 3:56:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


alter proc [HHSurvey].[mergeHouseholdDim2014]
as 
BEGIN

	;WITH cte AS 
	(
	SELECT 
		  CAST([hhid] as bigint) as HouseholdDimID
		  ,[hhid] AS [hhid]
		,[traveldate] AS [traveldate]
		,[dayofweek] AS [dayofweek]
		,[hhnumtrips] AS [hhnumtrips]
		,[vehicle_countValue] AS [vehicle_count]
		,[hhsizeValue] AS [hhsize]
		,[numadultsValue] AS [numadults]
		,[numchildrenValue] AS [numchildren]
		,[numworkers] AS [numworkers]
		,[lifecycleValue] AS [lifecycle]
		,[hh_income_detailedValue] AS [hh_income_detailed]
		,[hh_income_followupValue] AS [hh_income_followup]
		,[hh_income_broadValue] AS [hh_income_broad]
		,[hh_income_detailed_impValue] AS [hh_income_detailed_imp]
		,[hh_income_samp_estValue] AS [hh_income_samp_est]
		,[sample_segnameValue] AS [sample_segname]
		,[h_cntyValue] AS [h_cnty]
		,[h_city] AS [h_city]
		,[h_zip] AS [h_zip]
		,[address_use_flagValue] AS [address_use_flag]
		,[h_segnameValue] AS [h_segname]
		,[h_segname_wgtValue] AS [h_segname_wgt]
		,[h_county_name] AS [h_county_name]
		,[h_district_name] AS [h_district_name]
		,[h_rgc_name] AS [h_rgc_name]
		,[h_school_district_name] AS [h_school_district_name]
		,[h_uv_name] AS [h_uv_name]
		,[h_uv_groupValue] AS [h_uv_group]
		,[h_tract] AS [h_tract]
		,[h_bg] AS [h_bg]
		,[h_puma12Value] AS [h_puma12]
		,[res_monthsValue] AS [res_months]
		,[res_durValue] AS [res_dur]
		,[rent_ownValue] AS [rent_own]
		,[res_typeValue] AS [res_type]
		,[res_factors_hhchangeValue] AS [res_factors_hhchange]
		,[res_factors_affordValue] AS [res_factors_afford]
		,[res_factors_schoolValue] AS [res_factors_school]
		,[res_factors_walkValue] AS [res_factors_walk]
		,[res_factors_spaceValue] AS [res_factors_space]
		,[res_factors_closefamValue] AS [res_factors_closefam]
		,[res_factors_transitValue] AS [res_factors_transit]
		,[res_factors_hwyValue] AS [res_factors_hwy]
		,[res_factors_30minValue] AS [res_factors_30min]
		,[prev_rent_ownValue] AS [prev_rent_own]
		,[prev_res_typeValue] AS [prev_res_type]
		,[prev_home_waValue] AS [prev_home_wa]
		,[prev_home_loc_cntyValue] AS [prev_home_loc_cnty]
		,[prev_home_loc_city] AS [prev_home_loc_city]
		,[prev_home_loc_zip] AS [prev_home_loc_zip]
		,[prev_home_loc_st] AS [prev_home_loc_st]
		,[prev_tract] AS [prev_tract]
		,[prev_bg] AS [prev_bg]
		,[prev_puma12] AS [prev_puma12]
		,[prev_rgc_name] AS [prev_rgc_name]
		,[prev_home_loc_xValue] AS [prev_home_loc_x]
		,[cityofseattleValue] AS [cityofseattle]
		,[expwt_2] AS [expwt_2]
		,[datasetValue] AS [dataset]
		  ,BINARY_CHECKSUM(*) AS DWCHECKSUM
	  FROM [stg].[ResponseAndCodeHousehold_2014]
	)
	MERGE HHSurvey.HouseholdDim2014 AS target
	USING cte AS source
	ON
	(
		target.HouseholdDimID = source.HouseholdDimID
	)
	WHEN MATCHED AND COALESCE(target.DWCHECKSUM,-1) <> COALESCE(source.DWCHECKSUM, -1) THEN
		UPDATE SET
		target.[hhid] = source.[hhid]
		,target.[traveldate] = source.[traveldate]
		,target.[dayofweek] = source.[dayofweek]
		,target.[hhnumtrips] = source.[hhnumtrips]
		,target.[vehicle_count] = source.[vehicle_count]
		,target.[hhsize] = source.[hhsize]
		,target.[numadults] = source.[numadults]
		,target.[numchildren] = source.[numchildren]
		,target.[numworkers] = source.[numworkers]
		,target.[lifecycle] = source.[lifecycle]
		,target.[hh_income_detailed] = source.[hh_income_detailed]
		,target.[hh_income_followup] = source.[hh_income_followup]
		,target.[hh_income_broad] = source.[hh_income_broad]
		,target.[hh_income_detailed_imp] = source.[hh_income_detailed_imp]
		,target.[hh_income_samp_est] = source.[hh_income_samp_est]
		,target.[sample_segname] = source.[sample_segname]
		,target.[h_cnty] = source.[h_cnty]
		,target.[h_city] = source.[h_city]
		,target.[h_zip] = source.[h_zip]
		,target.[address_use_flag] = source.[address_use_flag]
		,target.[h_segname] = source.[h_segname]
		,target.[h_segname_wgt] = source.[h_segname_wgt]
		,target.[h_county_name] = source.[h_county_name]
		,target.[h_district_name] = source.[h_district_name]
		,target.[h_rgc_name] = source.[h_rgc_name]
		,target.[h_school_district_name] = source.[h_school_district_name]
		,target.[h_uv_name] = source.[h_uv_name]
		,target.[h_uv_group] = source.[h_uv_group]
		,target.[h_tract] = source.[h_tract]
		,target.[h_bg] = source.[h_bg]
		,target.[h_puma12] = source.[h_puma12]
		,target.[res_months] = source.[res_months]
		,target.[res_dur] = source.[res_dur]
		,target.[rent_own] = source.[rent_own]
		,target.[res_type] = source.[res_type]
		,target.[res_factors_hhchange] = source.[res_factors_hhchange]
		,target.[res_factors_afford] = source.[res_factors_afford]
		,target.[res_factors_school] = source.[res_factors_school]
		,target.[res_factors_walk] = source.[res_factors_walk]
		,target.[res_factors_space] = source.[res_factors_space]
		,target.[res_factors_closefam] = source.[res_factors_closefam]
		,target.[res_factors_transit] = source.[res_factors_transit]
		,target.[res_factors_hwy] = source.[res_factors_hwy]
		,target.[res_factors_30min] = source.[res_factors_30min]
		,target.[prev_rent_own] = source.[prev_rent_own]
		,target.[prev_res_type] = source.[prev_res_type]
		,target.[prev_home_wa] = source.[prev_home_wa]
		,target.[prev_home_loc_cnty] = source.[prev_home_loc_cnty]
		,target.[prev_home_loc_city] = source.[prev_home_loc_city]
		,target.[prev_home_loc_zip] = source.[prev_home_loc_zip]
		,target.[prev_home_loc_st] = source.[prev_home_loc_st]
		,target.[prev_tract] = source.[prev_tract]
		,target.[prev_bg] = source.[prev_bg]
		,target.[prev_puma12] = source.[prev_puma12]
		,target.[prev_rgc_name] = source.[prev_rgc_name]
		,target.[prev_home_loc_x] = source.[prev_home_loc_x]
		,target.[cityofseattle] = source.[cityofseattle]
		,target.[expwt_2] = source.[expwt_2]
		,target.[dataset] = source.[dataset]
	WHEN NOT MATCHED THEN INSERT (
		  HouseholdDimID
		 ,[hhid]
		,[traveldate]
		,[dayofweek]
		,[hhnumtrips]
		,[vehicle_count]
		,[hhsize]
		,[numadults]
		,[numchildren]
		,[numworkers]
		,[lifecycle]
		,[hh_income_detailed]
		,[hh_income_followup]
		,[hh_income_broad]
		,[hh_income_detailed_imp]
		,[hh_income_samp_est]
		,[sample_segname]
		,[h_cnty]
		,[h_city]
		,[h_zip]
		,[address_use_flag]
		,[h_segname]
		,[h_segname_wgt]
		,[h_county_name]
		,[h_district_name]
		,[h_rgc_name]
		,[h_school_district_name]
		,[h_uv_name]
		,[h_uv_group]
		,[h_tract]
		,[h_bg]
		,[h_puma12]
		,[res_months]
		,[res_dur]
		,[rent_own]
		,[res_type]
		,[res_factors_hhchange]
		,[res_factors_afford]
		,[res_factors_school]
		,[res_factors_walk]
		,[res_factors_space]
		,[res_factors_closefam]
		,[res_factors_transit]
		,[res_factors_hwy]
		,[res_factors_30min]
		,[prev_rent_own]
		,[prev_res_type]
		,[prev_home_wa]
		,[prev_home_loc_cnty]
		,[prev_home_loc_city]
		,[prev_home_loc_zip]
		,[prev_home_loc_st]
		,[prev_tract]
		,[prev_bg]
		,[prev_puma12]
		,[prev_rgc_name]
		,[prev_home_loc_x]
		,[cityofseattle]
		,[expwt_2]
		,[dataset]
		,[DWCHECKSUM]
	)
	VALUES
	(
		source.HouseholdDimID
		,source.[hhid]
		,source.[traveldate]
		,source.[dayofweek]
		,source.[hhnumtrips]
		,source.[vehicle_count]
		,source.[hhsize]
		,source.[numadults]
		,source.[numchildren]
		,source.[numworkers]
		,source.[lifecycle]
		,source.[hh_income_detailed]
		,source.[hh_income_followup]
		,source.[hh_income_broad]
		,source.[hh_income_detailed_imp]
		,source.[hh_income_samp_est]
		,source.[sample_segname]
		,source.[h_cnty]
		,source.[h_city]
		,source.[h_zip]
		,source.[address_use_flag]
		,source.[h_segname]
		,source.[h_segname_wgt]
		,source.[h_county_name]
		,source.[h_district_name]
		,source.[h_rgc_name]
		,source.[h_school_district_name]
		,source.[h_uv_name]
		,source.[h_uv_group]
		,source.[h_tract]
		,source.[h_bg]
		,source.[h_puma12]
		,source.[res_months]
		,source.[res_dur]
		,source.[rent_own]
		,source.[res_type]
		,source.[res_factors_hhchange]
		,source.[res_factors_afford]
		,source.[res_factors_school]
		,source.[res_factors_walk]
		,source.[res_factors_space]
		,source.[res_factors_closefam]
		,source.[res_factors_transit]
		,source.[res_factors_hwy]
		,source.[res_factors_30min]
		,source.[prev_rent_own]
		,source.[prev_res_type]
		,source.[prev_home_wa]
		,source.[prev_home_loc_cnty]
		,source.[prev_home_loc_city]
		,source.[prev_home_loc_zip]
		,source.[prev_home_loc_st]
		,source.[prev_tract]
		,source.[prev_bg]
		,source.[prev_puma12]
		,source.[prev_rgc_name]
		,source.[prev_home_loc_x]
		,source.[cityofseattle]
		,source.[expwt_2]
		,source.[dataset]
		,source.[DWCHECKSUM]
	);

END
GO


