USE [Elmer]
GO

/****** Object:  StoredProcedure [dbo].[mergeHouseholdDim2014]    Script Date: 9/11/2019 1:12:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE proc [HHSurvey].[mergePersonDim2014]
as 
BEGIN

	;WITH cte AS 
	(
	SELECT 
		 CAST(Personid as bigint) as PersonDimID
		 ,[personid] AS [personid]
		,[hhid] AS [hhid]
		,[pernum] AS [pernum]
		,[person_should_take_diaryValue] AS [person_should_take_diary]
		,[person_diary_statusValue] AS [person_diary_status]
		,[proxyValue] AS [proxy]
		,[resptypeValue] AS [resptype]
		,[ageValue] AS [age]
		,[relationshipValue] AS [relationship]
		,[genderValue] AS [gender]
		,[employmentValue] AS [employment]
		,[jobs_countValue] AS [jobs_count]
		,[workerValue] AS [worker]
		,[studentValue] AS [student]
		,[studentind] AS [studentind]
		,[schoolValue] AS [school]
		,[educationValue] AS [education]
		,[smartphoneValue] AS [smartphone]
		,[licenseValue] AS [license]
		,[vehicleValue] AS [vehicle]
		,[tollfreqValue] AS [tollfreq]
		,[work_loc_cntyValue] AS [work_loc_cnty]
		,[work_loc_city] AS [work_loc_city]
		,[work_loc_zip] AS [work_loc_zip]
		,[work_loc_st] AS [work_loc_st]
		,[work_loc_tract] AS [work_loc_tract]
		,[work_loc_bg] AS [work_loc_bg]
		,[work_loc_PUMACE10] AS [work_loc_PUMACE10]
		,[work_loc_rgc_name] AS [work_loc_rgc_name]
		,[school_freqValue] AS [school_freq]
		,[school_cntyValue] AS [school_cnty]
		,[school_city] AS [school_city]
		,[school_zip] AS [school_zip]
		,[school_st] AS [school_st]
		,[school_tract] AS [school_tract]
		,[school_BG] AS [school_BG]
		,[school_PUMACE10] AS [school_PUMACE10]
		,[school_rgc_name] AS [school_rgc_name]
		,[trips_yesnoValue] AS [trips_yesno]
		,[numtrips] AS [numtrips]
		,[loc_startValue] AS [loc_start]
		,[loc_endValue] AS [loc_end]
		,[no_travelValue] AS [no_travel]
		,[noneed_dayoffValue] AS [noneed_dayoff]
		,[noneed_telecommuteValue] AS [noneed_telecommute]
		,[noneed_workhomenoapayValue] AS [noneed_workhomenoapay]
		,[noneed_kidsvacationValue] AS [noneed_kidsvacation]
		,[noneed_otherValue] AS [noneed_other]
		,[unable_notransportValue] AS [unable_notransport]
		,[unable_sickValue] AS [unable_sick]
		,[unable_visitorValue] AS [unable_visitor]
		,[unable_otherValue] AS [unable_other]
		,[added_trip_flagValue] AS [added_trip_flag]
		,[added_loopValue] AS [added_loop]
		,[added_quickValue] AS [added_quick]
		,[added_stopValue] AS [added_stop]
		,[added_dropoffValue] AS [added_dropoff]
		,[added_parkingValue] AS [added_parking]
		,[added_otherValue] AS [added_other]
		,[typicalValue] AS [typical]
		,[purchaseValue] AS [purchase]
		,[telecommuteValue] AS [telecommute]
		,[telecommute_hours] AS [telecommute_hours]
		,[transit_freqValue] AS [transit_freq]
		,[bike_freqValue] AS [bike_freq]
		,[walk_freqValue] AS [walk_freq]
		,[transitpay_orcaValue] AS [transitpay_orca]
		,[transitpay_cashValue] AS [transitpay_cash]
		,[transitpay_ticketsValue] AS [transitpay_tickets]
		,[transitpay_upassValue] AS [transitpay_upass]
		,[transitpay_permitValue] AS [transitpay_permit]
		,[transitpay_flexValue] AS [transitpay_flex]
		,[transitpay_accessValue] AS [transitpay_access]
		,[transitpay_schoolValue] AS [transitpay_school]
		,[transitpay_govtValue] AS [transitpay_govt]
		,[transitpay_otherValue] AS [transitpay_other]
		,[transitpay_dontknowValue] AS [transitpay_dontknow]
		,[transitpay_other_specify] AS [transitpay_other_specify]
		,[transit_subsidyValue] AS [transit_subsidy]
		,[hours_workValue] AS [hours_work]
		,[commute_freqValue] AS [commute_freq]
		,[telecommute_freqValue] AS [telecommute_freq]
		,[commute_durValue] AS [commute_dur]
		,[selfemp_durValue] AS [selfemp_dur]
		,[drive_livingValue] AS [drive_living]
		,[night_shiftValue] AS [night_shift]
		,[choose_workValue] AS [choose_work]
		,[choose_weatherValue] AS [choose_weather]
		,[benefits_flextimeValue] AS [benefits_flextime]
		,[benefits_compressedValue] AS [benefits_compressed]
		,[benefits_parkingValue] AS [benefits_parking]
		,[benefits_transitValue] AS [benefits_transit]
		,[benefits_commuteValue] AS [benefits_commute]
		,[prev_work_waValue] AS [prev_work_wa]
		,[prev_work_loc_cntyValue] AS [prev_work_loc_cnty]
		,[prev_work_loc_city] AS [prev_work_loc_city]
		,[prev_work_loc_zip] AS [prev_work_loc_zip]
		,[prev_work_loc_st] AS [prev_work_loc_st]
		,[prev_work_loc_tract] AS [prev_work_loc_tract]
		,[prev_work_loc_BG] AS [prev_work_loc_BG]
		,[prev_work_loc_PUMACE10] AS [prev_work_loc_PUMACE10]
		,[prev_work_rgc_name] AS [prev_work_rgc_name]
		,[prev_work_loc_xValue] AS [prev_work_loc_x]
		,[smartphone_typeValue] AS [smartphone_type]
		,[smartphone_type6_r] AS [smartphone_type6_r]
		,[smartphone_drValue] AS [smartphone_dr]
		,[smartphone_dr14_r] AS [smartphone_dr14_r]
		,[smartphone_ipValue] AS [smartphone_ip]
		,[smartphone_ip9_r] AS [smartphone_ip9_r]
		,[website_useValue] AS [website_use]
		,[phonenumber_useValue] AS [phonenumber_use]
		,[apps_useValue] AS [apps_use]
		,[alerts_useValue] AS [alerts_use]
		,[socialmedia_useValue] AS [socialmedia_use]
		,[radio_useValue] AS [radio_use]
		,[tv_useValue] AS [tv_use]
		,[gps_useValue] AS [gps_use]
		,[web_bingValue] AS [web_bing]
		,[web_googleValue] AS [web_google]
		,[web_mapquestValue] AS [web_mapquest]
		,[web_trafficValue] AS [web_traffic]
		,[web_wsdotValue] AS [web_wsdot]
		,[web_countyValue] AS [web_county]
		,[web_cityValue] AS [web_city]
		,[web_transitValue] AS [web_transit]
		,[web_otherValue] AS [web_other]
		,[web_other_specify] AS [web_other_specify]
		,[apps_seattletrafficValue] AS [apps_seattletraffic]
		,[apps_wazeValue] AS [apps_waze]
		,[apps_wsdotValue] AS [apps_wsdot]
		,[apps_onebusawayValue] AS [apps_onebusaway]
		,[apps_inrixValue] AS [apps_inrix]
		,[apps_carshareValue] AS [apps_carshare]
		,[apps_taxiValue] AS [apps_taxi]
		,[apps_otherValue] AS [apps_other]
		,[apps_other_specify] AS [apps_other_specify]
		,[info_travelroutesValue] AS [info_travelroutes]
		,[info_traveltimeValue] AS [info_traveltime]
		,[info_congestionValue] AS [info_congestion]
		,[info_arrivaltimeValue] AS [info_arrivaltime]
		,[info_transitoptionsValue] AS [info_transitoptions]
		,[info_parkingValue] AS [info_parking]
		,[info_carshareValue] AS [info_carshare]
		,[info_otherValue] AS [info_other]
		,[info_other_specify] AS [info_other_specify]
		,[impact_sametripValue] AS [impact_sametrip]
		,[impact_earlierValue] AS [impact_earlier]
		,[impact_laterValue] AS [impact_later]
		,[impact_diffrouteValue] AS [impact_diffroute]
		,[impact_smallchangeValue] AS [impact_smallchange]
		,[impact_diffmodeValue] AS [impact_diffmode]
		,[impact_postponeValue] AS [impact_postpone]
		,[impact_orderValue] AS [impact_order]
		,[wbt_transitsafetyValue] AS [wbt_transitsafety]
		,[wbt_transitfreqValue] AS [wbt_transitfreq]
		,[wbt_reliabilityValue] AS [wbt_reliability]
		,[wbt_bikesafetyValue] AS [wbt_bikesafety]
		,[wbt_walksafetyValue] AS [wbt_walksafety]
		,[wbt_otherValue] AS [wbt_other]
		,[wbt_other_specify] AS [wbt_other_specify]
		,[wbt_noneValue] AS [wbt_none]
		,[wbt_naValue] AS [wbt_na]
		,[carpool_gascostValue] AS [carpool_gascost]
		,[carpool_parkingcostValue] AS [carpool_parkingcost]
		,[carpool_tollsValue] AS [carpool_tolls]
		,[carpool_hovValue] AS [carpool_hov]
		,[transit_availValue] AS [transit_avail]
		,[carpool_otherValue] AS [carpool_other]
		,[carpool_other_specify] AS [carpool_other_specify]
		,[carpool_noneValue] AS [carpool_none]
		,[carpool_naValue] AS [carpool_na]
		,[expwt_final] AS [expwt_final]
		,[datasetValue] AS [dataset]
		  ,BINARY_CHECKSUM(*) AS DWCHECKSUM
	  FROM [stg].[ResponseAndCodePerson_2014]
	)
	MERGE HHSurvey.PersonDim2014 AS target
	USING cte AS source
	ON
	(
		target.PersonDimID = source.PersonDimID
	)
	WHEN MATCHED AND COALESCE(target.DWCHECKSUM,-1) <> COALESCE(source.DWCHECKSUM, -1) THEN
		UPDATE SET
		target.[personid] = source.[personid]
		,target.[hhid] = source.[hhid]
		,target.[pernum] = source.[pernum]
		,target.[person_should_take_diary] = source.[person_should_take_diary]
		,target.[person_diary_status] = source.[person_diary_status]
		,target.[proxy] = source.[proxy]
		,target.[resptype] = source.[resptype]
		,target.[age] = source.[age]
		,target.[relationship] = source.[relationship]
		,target.[gender] = source.[gender]
		,target.[employment] = source.[employment]
		,target.[jobs_count] = source.[jobs_count]
		,target.[worker] = source.[worker]
		,target.[student] = source.[student]
		,target.[studentind] = source.[studentind]
		,target.[school] = source.[school]
		,target.[education] = source.[education]
		,target.[smartphone] = source.[smartphone]
		,target.[license] = source.[license]
		,target.[vehicle] = source.[vehicle]
		,target.[tollfreq] = source.[tollfreq]
		,target.[work_loc_cnty] = source.[work_loc_cnty]
		,target.[work_loc_city] = source.[work_loc_city]
		,target.[work_loc_zip] = source.[work_loc_zip]
		,target.[work_loc_st] = source.[work_loc_st]
		,target.[work_loc_tract] = source.[work_loc_tract]
		,target.[work_loc_bg] = source.[work_loc_bg]
		,target.[work_loc_PUMACE10] = source.[work_loc_PUMACE10]
		,target.[work_loc_rgc_name] = source.[work_loc_rgc_name]
		,target.[school_freq] = source.[school_freq]
		,target.[school_cnty] = source.[school_cnty]
		,target.[school_city] = source.[school_city]
		,target.[school_zip] = source.[school_zip]
		,target.[school_st] = source.[school_st]
		,target.[school_tract] = source.[school_tract]
		,target.[school_BG] = source.[school_BG]
		,target.[school_PUMACE10] = source.[school_PUMACE10]
		,target.[school_rgc_name] = source.[school_rgc_name]
		,target.[trips_yesno] = source.[trips_yesno]
		,target.[numtrips] = source.[numtrips]
		,target.[loc_start] = source.[loc_start]
		,target.[loc_end] = source.[loc_end]
		,target.[no_travel] = source.[no_travel]
		,target.[noneed_dayoff] = source.[noneed_dayoff]
		,target.[noneed_telecommute] = source.[noneed_telecommute]
		,target.[noneed_workhomenoapay] = source.[noneed_workhomenoapay]
		,target.[noneed_kidsvacation] = source.[noneed_kidsvacation]
		,target.[noneed_other] = source.[noneed_other]
		,target.[unable_notransport] = source.[unable_notransport]
		,target.[unable_sick] = source.[unable_sick]
		,target.[unable_visitor] = source.[unable_visitor]
		,target.[unable_other] = source.[unable_other]
		,target.[added_trip_flag] = source.[added_trip_flag]
		,target.[added_loop] = source.[added_loop]
		,target.[added_quick] = source.[added_quick]
		,target.[added_stop] = source.[added_stop]
		,target.[added_dropoff] = source.[added_dropoff]
		,target.[added_parking] = source.[added_parking]
		,target.[added_other] = source.[added_other]
		,target.[typical] = source.[typical]
		,target.[purchase] = source.[purchase]
		,target.[telecommute] = source.[telecommute]
		,target.[telecommute_hours] = source.[telecommute_hours]
		,target.[transit_freq] = source.[transit_freq]
		,target.[bike_freq] = source.[bike_freq]
		,target.[walk_freq] = source.[walk_freq]
		,target.[transitpay_orca] = source.[transitpay_orca]
		,target.[transitpay_cash] = source.[transitpay_cash]
		,target.[transitpay_tickets] = source.[transitpay_tickets]
		,target.[transitpay_upass] = source.[transitpay_upass]
		,target.[transitpay_permit] = source.[transitpay_permit]
		,target.[transitpay_flex] = source.[transitpay_flex]
		,target.[transitpay_access] = source.[transitpay_access]
		,target.[transitpay_school] = source.[transitpay_school]
		,target.[transitpay_govt] = source.[transitpay_govt]
		,target.[transitpay_other] = source.[transitpay_other]
		,target.[transitpay_dontknow] = source.[transitpay_dontknow]
		,target.[transitpay_other_specify] = source.[transitpay_other_specify]
		,target.[transit_subsidy] = source.[transit_subsidy]
		,target.[hours_work] = source.[hours_work]
		,target.[commute_freq] = source.[commute_freq]
		,target.[telecommute_freq] = source.[telecommute_freq]
		,target.[commute_dur] = source.[commute_dur]
		,target.[selfemp_dur] = source.[selfemp_dur]
		,target.[drive_living] = source.[drive_living]
		,target.[night_shift] = source.[night_shift]
		,target.[choose_work] = source.[choose_work]
		,target.[choose_weather] = source.[choose_weather]
		,target.[benefits_flextime] = source.[benefits_flextime]
		,target.[benefits_compressed] = source.[benefits_compressed]
		,target.[benefits_parking] = source.[benefits_parking]
		,target.[benefits_transit] = source.[benefits_transit]
		,target.[benefits_commute] = source.[benefits_commute]
		,target.[prev_work_wa] = source.[prev_work_wa]
		,target.[prev_work_loc_cnty] = source.[prev_work_loc_cnty]
		,target.[prev_work_loc_city] = source.[prev_work_loc_city]
		,target.[prev_work_loc_zip] = source.[prev_work_loc_zip]
		,target.[prev_work_loc_st] = source.[prev_work_loc_st]
		,target.[prev_work_loc_tract] = source.[prev_work_loc_tract]
		,target.[prev_work_loc_BG] = source.[prev_work_loc_BG]
		,target.[prev_work_loc_PUMACE10] = source.[prev_work_loc_PUMACE10]
		,target.[prev_work_rgc_name] = source.[prev_work_rgc_name]
		,target.[prev_work_loc_x] = source.[prev_work_loc_x]
		,target.[smartphone_type] = source.[smartphone_type]
		,target.[smartphone_type6_r] = source.[smartphone_type6_r]
		,target.[smartphone_dr] = source.[smartphone_dr]
		,target.[smartphone_dr14_r] = source.[smartphone_dr14_r]
		,target.[smartphone_ip] = source.[smartphone_ip]
		,target.[smartphone_ip9_r] = source.[smartphone_ip9_r]
		,target.[website_use] = source.[website_use]
		,target.[phonenumber_use] = source.[phonenumber_use]
		,target.[apps_use] = source.[apps_use]
		,target.[alerts_use] = source.[alerts_use]
		,target.[socialmedia_use] = source.[socialmedia_use]
		,target.[radio_use] = source.[radio_use]
		,target.[tv_use] = source.[tv_use]
		,target.[gps_use] = source.[gps_use]
		,target.[web_bing] = source.[web_bing]
		,target.[web_google] = source.[web_google]
		,target.[web_mapquest] = source.[web_mapquest]
		,target.[web_traffic] = source.[web_traffic]
		,target.[web_wsdot] = source.[web_wsdot]
		,target.[web_county] = source.[web_county]
		,target.[web_city] = source.[web_city]
		,target.[web_transit] = source.[web_transit]
		,target.[web_other] = source.[web_other]
		,target.[web_other_specify] = source.[web_other_specify]
		,target.[apps_seattletraffic] = source.[apps_seattletraffic]
		,target.[apps_waze] = source.[apps_waze]
		,target.[apps_wsdot] = source.[apps_wsdot]
		,target.[apps_onebusaway] = source.[apps_onebusaway]
		,target.[apps_inrix] = source.[apps_inrix]
		,target.[apps_carshare] = source.[apps_carshare]
		,target.[apps_taxi] = source.[apps_taxi]
		,target.[apps_other] = source.[apps_other]
		,target.[apps_other_specify] = source.[apps_other_specify]
		,target.[info_travelroutes] = source.[info_travelroutes]
		,target.[info_traveltime] = source.[info_traveltime]
		,target.[info_congestion] = source.[info_congestion]
		,target.[info_arrivaltime] = source.[info_arrivaltime]
		,target.[info_transitoptions] = source.[info_transitoptions]
		,target.[info_parking] = source.[info_parking]
		,target.[info_carshare] = source.[info_carshare]
		,target.[info_other] = source.[info_other]
		,target.[info_other_specify] = source.[info_other_specify]
		,target.[impact_sametrip] = source.[impact_sametrip]
		,target.[impact_earlier] = source.[impact_earlier]
		,target.[impact_later] = source.[impact_later]
		,target.[impact_diffroute] = source.[impact_diffroute]
		,target.[impact_smallchange] = source.[impact_smallchange]
		,target.[impact_diffmode] = source.[impact_diffmode]
		,target.[impact_postpone] = source.[impact_postpone]
		,target.[impact_order] = source.[impact_order]
		,target.[wbt_transitsafety] = source.[wbt_transitsafety]
		,target.[wbt_transitfreq] = source.[wbt_transitfreq]
		,target.[wbt_reliability] = source.[wbt_reliability]
		,target.[wbt_bikesafety] = source.[wbt_bikesafety]
		,target.[wbt_walksafety] = source.[wbt_walksafety]
		,target.[wbt_other] = source.[wbt_other]
		,target.[wbt_other_specify] = source.[wbt_other_specify]
		,target.[wbt_none] = source.[wbt_none]
		,target.[wbt_na] = source.[wbt_na]
		,target.[carpool_gascost] = source.[carpool_gascost]
		,target.[carpool_parkingcost] = source.[carpool_parkingcost]
		,target.[carpool_tolls] = source.[carpool_tolls]
		,target.[carpool_hov] = source.[carpool_hov]
		,target.[transit_avail] = source.[transit_avail]
		,target.[carpool_other] = source.[carpool_other]
		,target.[carpool_other_specify] = source.[carpool_other_specify]
		,target.[carpool_none] = source.[carpool_none]
		,target.[carpool_na] = source.[carpool_na]
		,target.[expwt_final] = source.[expwt_final]
		,target.[dataset] = source.[dataset]
		,target.[DWCHECKSUM] = source.[DWCHECKSUM]
	WHEN NOT MATCHED THEN INSERT (
		PersonDimID
		,[personid]
		,[hhid]
		,[pernum]
		,[person_should_take_diary]
		,[person_diary_status]
		,[proxy]
		,[resptype]
		,[age]
		,[relationship]
		,[gender]
		,[employment]
		,[jobs_count]
		,[worker]
		,[student]
		,[studentind]
		,[school]
		,[education]
		,[smartphone]
		,[license]
		,[vehicle]
		,[tollfreq]
		,[work_loc_cnty]
		,[work_loc_city]
		,[work_loc_zip]
		,[work_loc_st]
		,[work_loc_tract]
		,[work_loc_bg]
		,[work_loc_PUMACE10]
		,[work_loc_rgc_name]
		,[school_freq]
		,[school_cnty]
		,[school_city]
		,[school_zip]
		,[school_st]
		,[school_tract]
		,[school_BG]
		,[school_PUMACE10]
		,[school_rgc_name]
		,[trips_yesno]
		,[numtrips]
		,[loc_start]
		,[loc_end]
		,[no_travel]
		,[noneed_dayoff]
		,[noneed_telecommute]
		,[noneed_workhomenoapay]
		,[noneed_kidsvacation]
		,[noneed_other]
		,[unable_notransport]
		,[unable_sick]
		,[unable_visitor]
		,[unable_other]
		,[added_trip_flag]
		,[added_loop]
		,[added_quick]
		,[added_stop]
		,[added_dropoff]
		,[added_parking]
		,[added_other]
		,[typical]
		,[purchase]
		,[telecommute]
		,[telecommute_hours]
		,[transit_freq]
		,[bike_freq]
		,[walk_freq]
		,[transitpay_orca]
		,[transitpay_cash]
		,[transitpay_tickets]
		,[transitpay_upass]
		,[transitpay_permit]
		,[transitpay_flex]
		,[transitpay_access]
		,[transitpay_school]
		,[transitpay_govt]
		,[transitpay_other]
		,[transitpay_dontknow]
		,[transitpay_other_specify]
		,[transit_subsidy]
		,[hours_work]
		,[commute_freq]
		,[telecommute_freq]
		,[commute_dur]
		,[selfemp_dur]
		,[drive_living]
		,[night_shift]
		,[choose_work]
		,[choose_weather]
		,[benefits_flextime]
		,[benefits_compressed]
		,[benefits_parking]
		,[benefits_transit]
		,[benefits_commute]
		,[prev_work_wa]
		,[prev_work_loc_cnty]
		,[prev_work_loc_city]
		,[prev_work_loc_zip]
		,[prev_work_loc_st]
		,[prev_work_loc_tract]
		,[prev_work_loc_BG]
		,[prev_work_loc_PUMACE10]
		,[prev_work_rgc_name]
		,[prev_work_loc_x]
		,[smartphone_type]
		,[smartphone_type6_r]
		,[smartphone_dr]
		,[smartphone_dr14_r]
		,[smartphone_ip]
		,[smartphone_ip9_r]
		,[website_use]
		,[phonenumber_use]
		,[apps_use]
		,[alerts_use]
		,[socialmedia_use]
		,[radio_use]
		,[tv_use]
		,[gps_use]
		,[web_bing]
		,[web_google]
		,[web_mapquest]
		,[web_traffic]
		,[web_wsdot]
		,[web_county]
		,[web_city]
		,[web_transit]
		,[web_other]
		,[web_other_specify]
		,[apps_seattletraffic]
		,[apps_waze]
		,[apps_wsdot]
		,[apps_onebusaway]
		,[apps_inrix]
		,[apps_carshare]
		,[apps_taxi]
		,[apps_other]
		,[apps_other_specify]
		,[info_travelroutes]
		,[info_traveltime]
		,[info_congestion]
		,[info_arrivaltime]
		,[info_transitoptions]
		,[info_parking]
		,[info_carshare]
		,[info_other]
		,[info_other_specify]
		,[impact_sametrip]
		,[impact_earlier]
		,[impact_later]
		,[impact_diffroute]
		,[impact_smallchange]
		,[impact_diffmode]
		,[impact_postpone]
		,[impact_order]
		,[wbt_transitsafety]
		,[wbt_transitfreq]
		,[wbt_reliability]
		,[wbt_bikesafety]
		,[wbt_walksafety]
		,[wbt_other]
		,[wbt_other_specify]
		,[wbt_none]
		,[wbt_na]
		,[carpool_gascost]
		,[carpool_parkingcost]
		,[carpool_tolls]
		,[carpool_hov]
		,[transit_avail]
		,[carpool_other]
		,[carpool_other_specify]
		,[carpool_none]
		,[carpool_na]
		,[expwt_final]
		,[dataset]
		,[DWCHECKSUM]
	)
	VALUES
	(
		source.[PersonDimID]
		,source.[personid]
		,source.[hhid]
		,source.[pernum]
		,source.[person_should_take_diary]
		,source.[person_diary_status]
		,source.[proxy]
		,source.[resptype]
		,source.[age]
		,source.[relationship]
		,source.[gender]
		,source.[employment]
		,source.[jobs_count]
		,source.[worker]
		,source.[student]
		,source.[studentind]
		,source.[school]
		,source.[education]
		,source.[smartphone]
		,source.[license]
		,source.[vehicle]
		,source.[tollfreq]
		,source.[work_loc_cnty]
		,source.[work_loc_city]
		,source.[work_loc_zip]
		,source.[work_loc_st]
		,source.[work_loc_tract]
		,source.[work_loc_bg]
		,source.[work_loc_PUMACE10]
		,source.[work_loc_rgc_name]
		,source.[school_freq]
		,source.[school_cnty]
		,source.[school_city]
		,source.[school_zip]
		,source.[school_st]
		,source.[school_tract]
		,source.[school_BG]
		,source.[school_PUMACE10]
		,source.[school_rgc_name]
		,source.[trips_yesno]
		,source.[numtrips]
		,source.[loc_start]
		,source.[loc_end]
		,source.[no_travel]
		,source.[noneed_dayoff]
		,source.[noneed_telecommute]
		,source.[noneed_workhomenoapay]
		,source.[noneed_kidsvacation]
		,source.[noneed_other]
		,source.[unable_notransport]
		,source.[unable_sick]
		,source.[unable_visitor]
		,source.[unable_other]
		,source.[added_trip_flag]
		,source.[added_loop]
		,source.[added_quick]
		,source.[added_stop]
		,source.[added_dropoff]
		,source.[added_parking]
		,source.[added_other]
		,source.[typical]
		,source.[purchase]
		,source.[telecommute]
		,source.[telecommute_hours]
		,source.[transit_freq]
		,source.[bike_freq]
		,source.[walk_freq]
		,source.[transitpay_orca]
		,source.[transitpay_cash]
		,source.[transitpay_tickets]
		,source.[transitpay_upass]
		,source.[transitpay_permit]
		,source.[transitpay_flex]
		,source.[transitpay_access]
		,source.[transitpay_school]
		,source.[transitpay_govt]
		,source.[transitpay_other]
		,source.[transitpay_dontknow]
		,source.[transitpay_other_specify]
		,source.[transit_subsidy]
		,source.[hours_work]
		,source.[commute_freq]
		,source.[telecommute_freq]
		,source.[commute_dur]
		,source.[selfemp_dur]
		,source.[drive_living]
		,source.[night_shift]
		,source.[choose_work]
		,source.[choose_weather]
		,source.[benefits_flextime]
		,source.[benefits_compressed]
		,source.[benefits_parking]
		,source.[benefits_transit]
		,source.[benefits_commute]
		,source.[prev_work_wa]
		,source.[prev_work_loc_cnty]
		,source.[prev_work_loc_city]
		,source.[prev_work_loc_zip]
		,source.[prev_work_loc_st]
		,source.[prev_work_loc_tract]
		,source.[prev_work_loc_BG]
		,source.[prev_work_loc_PUMACE10]
		,source.[prev_work_rgc_name]
		,source.[prev_work_loc_x]
		,source.[smartphone_type]
		,source.[smartphone_type6_r]
		,source.[smartphone_dr]
		,source.[smartphone_dr14_r]
		,source.[smartphone_ip]
		,source.[smartphone_ip9_r]
		,source.[website_use]
		,source.[phonenumber_use]
		,source.[apps_use]
		,source.[alerts_use]
		,source.[socialmedia_use]
		,source.[radio_use]
		,source.[tv_use]
		,source.[gps_use]
		,source.[web_bing]
		,source.[web_google]
		,source.[web_mapquest]
		,source.[web_traffic]
		,source.[web_wsdot]
		,source.[web_county]
		,source.[web_city]
		,source.[web_transit]
		,source.[web_other]
		,source.[web_other_specify]
		,source.[apps_seattletraffic]
		,source.[apps_waze]
		,source.[apps_wsdot]
		,source.[apps_onebusaway]
		,source.[apps_inrix]
		,source.[apps_carshare]
		,source.[apps_taxi]
		,source.[apps_other]
		,source.[apps_other_specify]
		,source.[info_travelroutes]
		,source.[info_traveltime]
		,source.[info_congestion]
		,source.[info_arrivaltime]
		,source.[info_transitoptions]
		,source.[info_parking]
		,source.[info_carshare]
		,source.[info_other]
		,source.[info_other_specify]
		,source.[impact_sametrip]
		,source.[impact_earlier]
		,source.[impact_later]
		,source.[impact_diffroute]
		,source.[impact_smallchange]
		,source.[impact_diffmode]
		,source.[impact_postpone]
		,source.[impact_order]
		,source.[wbt_transitsafety]
		,source.[wbt_transitfreq]
		,source.[wbt_reliability]
		,source.[wbt_bikesafety]
		,source.[wbt_walksafety]
		,source.[wbt_other]
		,source.[wbt_other_specify]
		,source.[wbt_none]
		,source.[wbt_na]
		,source.[carpool_gascost]
		,source.[carpool_parkingcost]
		,source.[carpool_tolls]
		,source.[carpool_hov]
		,source.[transit_avail]
		,source.[carpool_other]
		,source.[carpool_other_specify]
		,source.[carpool_none]
		,source.[carpool_na]
		,source.[expwt_final]
		,source.[dataset]
		,source.[DWCHECKSUM]
	);

END
GO


