DROP TABLE IF EXISTS HHSurvey.PersonDim2017
CREATE TABLE HHSurvey.PersonDim2017 (
	PersonDimID bigint
	,[hhid] [BIGINT]
	,[personid] [BIGINT]
	,[pernum] [TINYINT]
	,[sample_segment] [VARCHAR](100)
	,[hhgroup] [VARCHAR](20)
	,[traveldate] [DATETIME2]
	,[relationship] [VARCHAR](100)
	,[proxy_parent] [VARCHAR](20)
	,[proxy] [VARCHAR](100)
	,[age] [VARCHAR](100)
	,[gender] [VARCHAR](100)
	,[employment] [VARCHAR](100)
	,[jobs_count] [VARCHAR](100)
	,[worker] [VARCHAR](100)
	,[student] [VARCHAR](100)
	,[schooltype] [VARCHAR](100)
	,[education] [VARCHAR](100)
	,[license] [VARCHAR](100)
	,[vehicleused] [VARCHAR](100)
	,[smartphone_type] [VARCHAR](100)
	,[smartphone_age] [VARCHAR](20)
	,[smartphone_qualified] [VARCHAR](20)
	,[race_afam] [VARCHAR](100)
	,[race_aiak] [VARCHAR](100)
	,[race_asian] [VARCHAR](100)
	,[race_hapi] [VARCHAR](100)
	,[race_hisp] [VARCHAR](100)
	,[race_white] [VARCHAR](100)
	,[race_other] [VARCHAR](100)
	,[race_noanswer] [VARCHAR](100)
	,[workplace] [VARCHAR](100)
	,[hours_work] [VARCHAR](100)
	,[commute_freq] [VARCHAR](100)
	,[commute_mode] [VARCHAR](100)
	,[commute_dur] [VARCHAR](100)
	,[telecommute_freq] [VARCHAR](100)
	,[wpktyp] [VARCHAR](100)
	,[workpass] [VARCHAR](100)
	,[workpass_cost] [SMALLINT]
	,[workpass_cost_dk] [VARCHAR](100)
	,[work_county] [VARCHAR](100)
	,[work_tract] [BIGINT]
	,[work_bg] [BIGINT]
	,[work_puma10] [INT]
	,[work_rgcname] [VARCHAR](100)
	,[work_taz2010] [INT]
	,[prev_work_wa] [VARCHAR](100)
	,[prev_work_county] [VARCHAR](100)
	,[prev_work_tract] [BIGINT]
	,[prev_work_bg] [BIGINT]
	,[prev_work_puma10] [INT]
	,[prev_work_rgcname] [VARCHAR](100)
	,[prev_work_taz2010] [INT]
	,[prev_work_notwa_city] [VARCHAR](100)
	,[prev_work_notwa_zip] [INT]
	,[prev_work_notwa_state] [TINYINT]
	,[prev_work_notwa_notus] [VARCHAR](100)
	,[school_freq] [VARCHAR](100)
	,[school_loc_county] [VARCHAR](100)
	,[school_tract] [BIGINT]
	,[school_bg] [BIGINT]
	,[school_puma10] [INT]
	,[school_rgcname] [VARCHAR](100)
	,[school_taz2010] [INT]
	,[completed_pref_survey] [VARCHAR](20)
	,[mode_freq_1] [VARCHAR](100)
	,[mode_freq_2] [VARCHAR](100)
	,[mode_freq_3] [VARCHAR](100)
	,[mode_freq_4] [VARCHAR](100)
	,[mode_freq_5] [VARCHAR](100)
	,[tran_pass_1] [VARCHAR](100)
	,[tran_pass_2] [VARCHAR](100)
	,[tran_pass_3] [VARCHAR](100)
	,[tran_pass_4] [VARCHAR](100)
	,[tran_pass_5] [VARCHAR](100)
	,[tran_pass_6] [VARCHAR](100)
	,[tran_pass_7] [VARCHAR](100)
	,[tran_pass_8] [VARCHAR](100)
	,[tran_pass_9] [VARCHAR](100)
	,[tran_pass_10] [VARCHAR](100)
	,[tran_pass_11] [VARCHAR](100)
	,[tran_pass_12] [VARCHAR](100)
	,[benefits_1] [VARCHAR](100)
	,[benefits_2] [VARCHAR](100)
	,[benefits_3] [VARCHAR](100)
	,[benefits_4] [VARCHAR](100)
	,[av_interest_1] [VARCHAR](100)
	,[av_interest_2] [VARCHAR](100)
	,[av_interest_3] [VARCHAR](100)
	,[av_interest_4] [VARCHAR](100)
	,[av_interest_5] [VARCHAR](100)
	,[av_interest_6] [VARCHAR](100)
	,[av_interest_7] [VARCHAR](100)
	,[av_concern_1] [VARCHAR](100)
	,[av_concern_2] [VARCHAR](100)
	,[av_concern_3] [VARCHAR](100)
	,[av_concern_4] [VARCHAR](100)
	,[av_concern_5] [VARCHAR](100)
	,[wbt_transitmore_1] [VARCHAR](100)
	,[wbt_transitmore_2] [VARCHAR](100)
	,[wbt_transitmore_3] [VARCHAR](100)
	,[wbt_bikemore_1] [INT]
	,[wbt_bikemore_2] [INT]
	,[wbt_bikemore_3] [INT]
	,[wbt_bikemore_4] [INT]
	,[wbt_bikemore_5] [INT]
	,[rmove_incentive] [VARCHAR](100)
	,[call_center] [VARCHAR](20)
	,[mobile_device] [VARCHAR](20)
	,[num_trips] [SMALLINT]
	,[nwkdays] [VARCHAR](20)
	,[hh_wt_revised] [FLOAT]
	,[hh_day_wt_revised] [FLOAT]
	,[studentind] [CHAR](1)
	,DWCHECKSUM BIGINT
 ,CONSTRAINT [PK_PersonDim2017] PRIMARY KEY CLUSTERED (PersonDimID ASC)
)