drop table if exists HHSurvey.HouseholdDim2017
create table HHSurvey.HouseholdDim2017 (
	[HouseholdDimID] [BIGINT]
	,[hhid] [BIGINT]
	,[hhgroup] [varchar](20)
	,[sample_segment] [varchar](100)
	,[sample_county] [varchar](20)
	,[final_cnty] [varchar](20)
	,[cityofredmond] [varchar](20)
	,[cityofseattle] [varchar](20)
	,[psrc] [varchar](20)
	,[final_home_tract] [BIGINT]
	,[final_home_bg] [BIGINT]
	,[final_home_puma10] [INT]
	,[final_home_rgcnum] [TINYINT]
	,[final_home_uvnum] [TINYINT]
	,[final_home_taz2010] [SMALLINT]
	,[travelweek] [TINYINT]
	,[traveldate] [DATETIME2]
	,[dayofweek] [varchar](20)
	,[hhsize] [varchar](20)
	,[vehicle_count] [varchar](100)
	,[numadults] [TINYINT]
	,[numchildren] [TINYINT]
	,[numworkers] [TINYINT]
	,[lifecycle] [varchar](100)
	,[hhincome_detailed] [varchar](100)
	,[hhincome_followup] [varchar](100)
	,[hhincome_broad] [varchar](100)
	,[car_share] [varchar](20)
	,[rent_own] [varchar](100)
	,[res_dur] [varchar](100)
	,[res_type] [varchar](100)
	,[res_months] [varchar](100)
	,[offpark] [varchar](100)
	,[offpark_cost] [SMALLINT]
	,[streetpark] [varchar](100)
	,[prev_home_wa] [varchar](100)
	,[prev_home_tract] [BIGINT]
	,[prev_home_bg] [BIGINT]
	,[prev_home_puma10] [INT]
	,[prev_home_rgcname] [varchar](100)
	,[prev_home_taz2010] [SMALLINT]
	,[prev_home_notwa_notus] [varchar](100)
	,[prev_home_notwa_city] [varchar](100)
	,[prev_home_notwa_zip] [INT]
	,[prev_home_notwa_state] [TINYINT]
	,[prev_rent_own] [varchar](100)
	,[prev_res_type] [varchar](100)
	,[res_factors_30min] [varchar](100)
	,[res_factors_afford] [varchar](100)
	,[res_factors_closefam] [varchar](100)
	,[res_factors_hhchange] [varchar](100)
	,[res_factors_hwy] [varchar](100)
	,[res_factors_school] [varchar](100)
	,[res_factors_space] [varchar](100)
	,[res_factors_transit] [varchar](100)
	,[res_factors_walk] [varchar](100)
	,[rmove_optin] [varchar](100)
	,[diary_incentive_type] [varchar](100)
	,[extra_incentive] [varchar](100)
	,[call_center] [varchar](20)
	,[mobile_device] [varchar](20)
	,[contact_email] [varchar](100)
	,[contact_phone] [varchar](100)
	,[foreign_language] [varchar](20)
	,[google_translate] [varchar](20)
	,[recruit_start_pt] [TIME]
	,[recruit_end_pt] [TIME]
	,[recruit_duration_min] [INT]
	,[numdayscomplete] [varchar](20)
	,[day1complete] [varchar](20)
	,[day2complete] [varchar](20)
	,[day3complete] [varchar](20)
	,[day4complete] [varchar](20)
	,[day5complete] [varchar](20)
	,[day6complete] [varchar](20)
	,[day7complete] [varchar](20)
	,[num_trips] [TINYINT]
	,[nwkdays] [varchar](20)
	,[hh_wt_revised] [FLOAT]
	,[hh_day_wt_revised] [FLOAT]
	,DWCHECKSUM BIGINT
 CONSTRAINT [PK_HouseholdDim2017] PRIMARY KEY CLUSTERED (HouseholdDimID)
)